repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      -   id: mypy
          exclude: install-pdm.py
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      -   id: flake8
