version: '3.8'
services:
  postgres:
    image: postgres:11.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready -U krddevdays"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - webnet
    volumes:
      - .:/app

networks:
  webnet:
