version: 3.8
services:
  postgres:
    image: postgres:11.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready -U krddevdays"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migrations:
    image: krddevdays-app:latest
    command: [ "python3", "manage.py", "migrate" ]
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    networks:
      - webnet

  static:
    image: krddevdays-app:latest
    command: [ "python3", "manage.py", "collectstatic", "--noinput" ]
    volumes:
      - static_volume:/app/static/
    env_file:
      - .env
    networks:
      - webnet

  app:
    image: krddevdays-app:latest
    restart: on-failure
    env_file:
      - .env
    depends_on:
      static:
        condition: service_completed_successfully
      migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    networks:
      - webnet
    volumes:
      - static_volume:/app/static/

  nginx:
    image: krddevdays-nginx:latest
    volumes:
      - static_volume:/opt
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:

volumes:
  postgres_data:
  static_volume:
